name: smart_flutter_utils
description: Utility wrappers and extensions to make flutter easy and smart.
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_flutter_utils

version: 1.0.5

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  smart_http: ">=1.0.6 <2.0.0"

  equatable: ^2.0.7
  collection: ^1.18.0
  timeago: ^3.7.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  go_router: ^14.6.1
  formz: ^0.4.1
  get_storage: ^2.1.1
  bloc: ^8.1.4
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  lint: ^2.3.0
