name: smart_flutter_utils
description: Utility wrappers and extensions to make flutter easy and smart.
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_flutter_utils

version: 0.1.1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  collection: ^1.18.0
  timeago: ^3.6.1
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  lint: ^2.3.0
