name: smart_flutter_utils
description: Utility wrappers and extensions to make flutter easy and smart. 
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_flutter_utils

version: 0.0.8

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  collection: ^1.16.0
  timeago: ^3.3.0
  intl: ^0.17.0
  url_launcher: ^6.1.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.1
  