name: smart_http
description: A dart wrapper around dio to handle http requests along with cancelable api for bloc and repository.
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_http

version: 0.0.3

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.3
  http_parser: ^4.0.2
  mime_type: ^1.0.0
  path: ^1.8.3
  uuid: ^4.1.0

dev_dependencies:
  test: ^1.24.7
  lints: ^2.1.1
