name: smart_http
description: A dart wrapper around dio to handle http requests along with cancelable api for bloc and repository.
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_http

version: 1.0.5

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  http_parser: ^4.0.2
  mime_type: ^1.0.1
  path: ^1.9.0
  uuid: ^4.5.1
  equatable: ^2.0.7

dev_dependencies:
  test: ^1.25.9
  lint: ^2.3.0
