name: smart_flutter_widgets
description: Widget components and extensions to make flutter easy and smart.
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_flutter_widgets

version: 0.0.6

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  smart_flutter_utils: ^0.0.2

  auto_size_text: ^3.0.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  modal_bottom_sheet: ^2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  