name: smart_flutter_widgets
description: Widget components and extensions to make flutter easy and smart.
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_flutter_widgets

version: 0.1.2

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  smart_flutter_utils: ^0.0.9

  auto_size_text: ^3.0.0
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.1
  shimmer: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  