name: smart_flutter
description: A bundle package for all smart flutter packages including widgets, utils, etc. 
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_flutter

version: 0.1.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  smart_flutter_utils: ^0.0.5
  smart_flutter_widgets: ^0.1.1+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.1
  