name: smart_flutter
description: A bundle package for all smart flutter packages including widgets, utils, etc. 
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_flutter

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  smart_flutter_utils: ^1.0.0+1
  smart_flutter_widgets: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  lint: ^2.3.0
  