name: smart_flutter
description: A bundle package for all smart flutter packages including widgets, utils, etc. 
homepage: https://github.com/asadbaidar/smart
repository: https://github.com/asadbaidar/smart/tree/master/packages/smart_flutter

version: 0.1.4

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  smart_flutter_utils: ^0.1.1
  smart_flutter_widgets: ^0.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.3
  