name: example
description: An example project of smart_flutter_utils package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  smart_flutter_utils:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true