name: Publish smart_flutter_widgets

on:
  push:
    tags:
      - 'smart_flutter_widgets-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: asadbaidar/smart/.github/workflows/publish-flutter.yml@main
    with:
      working-directory: packages/smart_flutter_widgets
